FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . ./simulator/
ENV PYTHONPATH=/app
EXPOSE 8081
ENTRYPOINT ["python", "-m", "simulator"]
