GRANT CREATE SESSION TO pdbadmin;
GRANT CREATE TABLE TO pdbadmin;
GRANT CREATE SEQUENCE TO pdbadmin;
GRANT CREATE VIEW TO pdbadmin;
GRANT UNLIMITED TABLESPACE TO pdbadmin;
GRANT EXECUTE ON DBMS_AQ TO pdbadmin;
GRANT EXECUTE ON DBMS_AQADM TO pdbadmin;
GRANT AQ_ADMINISTRATOR_ROLE TO pdbadmin;
