driver=oracle.jdbc.OracleDriver
url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
username=pdbadmin
changeLogFile=changelog/db.changelog-master.yaml
defaultSchemaName=pdbadmin
liquibase.hub.mode=off
logLevel=INFO
